newrelic/k8s-agents-operator

.github/draft-image-release-config.yml, .github/workflows/draft-image-release.yml, .github/workflows/lint-pr.yml
Automate release notes and versioning
=> chore: Automate release notes

.github/workflows/repolinter.yml
Update Repolinter permissions after tightening repository's security settings
=> fix: Update Repolinter permissions

api/v1alpha1/instrumentation_webhook.go, cmd/main.go, go.mod, go.sum, internal/config/main.go, internal/config/main_test.go, internal/config/options.go, internal/version/main.go, internal/webhookhandler/webhookhandler.go, internal/webhookhandler/webhookhandler_suite_test.go, pkg/autodetect/main_test.go, pkg/instrumentation/dotnet.go, pkg/instrumentation/golang.go, pkg/instrumentation/javaagent.go, pkg/instrumentation/nodejs.go, pkg/instrumentation/php.go, pkg/instrumentation/podmutator.go, pkg/instrumentation/python.go, pkg/instrumentation/sdk.go, pkg/instrumentation/upgrade/upgrade.go, pkg/instrumentation/upgrade/upgrade_suite_test.go, pkg/instrumentation/upgrade/upgrade_test.go
Renaming Go module to uniquely identify our packages
=> feat: Create Go packages

.github/workflows/ci.yml
Automate Docker image builds with multi-architecture support
=> feat: Automate Docker image builds with multi-architecture support

.github/workflows/release-charts.yml
=> feat: Automate Helm chart builds

README.md, charts/k8s-agents-operator/README.md.gotmpl, charts/k8s-agents-operator/templates/NOTES.txt
=> feat: Document Helm chart

Makefile, src/api/v1alpha1/instrumentation_webhook_test.go, src/api/v1alpha1/webhook_suite_test.go
Unit testing for Go package `v1alpha1`
=> feat: Unit testing for package `v1alpha1`

Makefile, src/api/v1alpha1/propagators.go, src/api/v1alpha1/samplers.go, src/apm/golang.go, src/instrumentation/annotation_test.go, src/instrumentation/instrumentation_suite_test.go, src/instrumentation/podmutator_test.go, src/instrumentation/sdk_test.go
Unit testing for Go package `autodetect`
=> feat: Unit testing for package `autodetect`

charts/k8s-agents-operator/Chart.yaml, charts/k8s-agents-operator/README.md
=> feat: Bump versions

charts/k8s-agents-operator/templates/NOTES.txt
This PR corrects an old URL and a missing word in the NOTES.txt file.
=> fix: Edited NOTES.txt

src/apm/ruby.go
=> refactor: Update inject filename

.github/workflows/draft-image-release.yml
=> chore: Skip empty release

charts/k8s-agents-operator/README.md.gotmpl
=> docs: Update chart's `README.md`

tests/e2e/apps/dotnet_deployment.yaml, tests/e2e/apps/java_deployment.yaml, tests/e2e/apps/nodejs_deployment.yaml, tests/e2e/apps/python_deployment.yaml
=> chore: Add demo apps for E2E testing

tests/e2e/e2e-values.yml
E2E-specific installation values
=> test: E2E-specific installation values

tests/e2e/e2e-tests.sh
=> test: E2E test script

tests/e2e/README.md
=> test: E2E tests documentation

.github/workflows/ci.yml, tests/e2e/e2e-tests.sh
=> test: Automate E2E tests

charts/k8s-agents-operator/README.md
Add agent specific documentation and links.
=> docs: add agent specific documentation

.github/.golangci.yml, .github/workflows/ci.yml
=> feat: Lint Go files

charts/k8s-agents-operator/README.md, charts/k8s-agents-operator/README.md.gotmpl
=> docs: Update chart documentation

.github/workflows/ci.yml
=> feat: Lint Helm chart files

.github/renovate.json5
Configure Renovate dependency manager
=> feat: Configure Renovate dependency manager

tests/e2e/e2e-instrumentation.yml
Update E2E tests to use APM agents Docker repositories
=> test: Update E2E tests to use APM agents Docker repositories

charts/k8s-agents-operator/templates/deployment.yaml
=> chore: Fix newline

charts/k8s-agents-operator/README.md, charts/k8s-agents-operator/README.md.gotmpl, src/main.go, tests/e2e/e2e-instrumentation.yml, tests/kustomize/samples/instrumentation_v1alpha1_instrumentation.yaml
Use public Docker repositories
=> feat: Use public Docker repositories

.github/security.yml
=> feat: Security pipeline

charts/k8s-agents-operator/Chart.yaml, charts/k8s-agents-operator/README.md
Revert manual version bumps for release process to function correctly
=> fix: Revert manual chart version bumps

.github/ct.yaml, .github/workflows/ci.yml
=> feat: Replace helm lint with chart-testing-action

README.md
=> fix: Add forum link to README.md

.github/workflows/release-charts.yml
=> fix: Fix chart release workflow

src/apm/helper.go, src/apm/php.go, src/apm/php_test.go, src/internal/webhookhandler/webhookhandler_suite_test.go
Fixes env vars and how they get set.  This corrects an issue where a copy of an object is altered by a pointer ref but the copy is not returned.
=> fix: env conf incorrectly set

tests/e2e/apps/php_deployment.yaml, tests/e2e/e2e-instrumentation-php.yml, tests/e2e/e2e-tests.sh
=> feat: add php e2e tests

Tiltfile, charts/k8s-agents-operator/README.md, charts/k8s-agents-operator/README.md.gotmpl, charts/k8s-agents-operator/templates/_helpers.tpl, charts/k8s-agents-operator/templates/deployment.yaml, charts/k8s-agents-operator/tests/images_test.yaml, charts/k8s-agents-operator/values.yaml, tests/e2e/e2e-values.yml
=> feat: add digest support for images + docs updates

src/apm/health.go, src/apm/health_test.go
Updating to use a directory path to support multiple agent health files
=> chore: Update to use filepath instead of file

api/v1alpha2/instrumentation_conversion_test.go, cmd/main.go, internal/instrumentation/health.go, internal/instrumentation/health_check.go, internal/instrumentation/health_test.go, internal/instrumentation/util/worker/workers_test.go
=> fix: add some tests

api/v1alpha2/instrumentation_webhook.go, internal/version/main_test.go, tests/e2e/apps/php_deployment.yaml, tests/e2e/e2e-instrumentation-php.yml
=> fix: php 8.4

internal/apm/nodejs.go, internal/apm/nodejs_test.go
Fixes possible issue where injecting the nodejs agent could fail to mutate the pod with multiple mutating webhooks
=> fix: nodejs injector

internal/apm/python.go, internal/apm/python_test.go
Fixes possible issue where injecting the python agent could fail to mutate the pod with multiple mutating webhooks
=> fix: python injector

internal/apm/ruby.go, internal/apm/ruby_test.go
Fixes possible issue where injecting the ruby agent could fail to mutate the pod with multiple mutating webhooks
=> fix: ruby injector

instrumentation.md
Adjusted the container type, the APM agent is injected by an init container not by a sidecar
=> feat: Update instrumentation.md
